"""init

Revision ID: f8d7ce4ceb8b
Revises: abad6b1071e4
Create Date: 2026-04-19 03:17:15.788905

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f8d7ce4ceb8b"
down_revision: Union[str, Sequence[str], None] = "abad6b1071e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
